[tool.poetry]
name = "api-management-utils"
version = "0.1.0"
description = ""
authors = ["Laurence Smith <laurence.smith@airelogic.com>"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
jinja2 = "^3.1.2"
requests = "^2.32.4"
flake8 = "^3.7.9"
mypy = "^0.770"
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
ansible = "^2.9.23rc1"
pyyaml = "^6.0"
jmespath = "^0.10.0"
awscli = "^1.18.80"
pydantic = "^1.9.0"
deepdiff = "^5.0.2"
semver = "^2.13.0"
gitpython = "^3.1.11"
pytest-xdist = "^1.10.0"
lxml = "^4.6.2"
docker = "^7.1.0"
boto3 = "^1.26.20"

[tool.poetry.dev-dependencies]
ansible-lint = "^4.2.0"
black = "^24.3.0"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
